name = "sem-content-tools"
type = "webpack"
workers_dev = true
route = "app.semcontent.tools/*"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
# Add your production environment variables here
# Example:
# MY_VARIABLE = "production_value"

[env.staging]
# Add your staging environment variables here
# Example:
# MY_VARIABLE = "staging_value" 